### PR TITLE
Artifactory on Swarm

### PR DESCRIPTION
**Pull request by mfuxi**
Added Artifactory on swarm (only one leader at the moment)
If there's anything else you would like me to add or fix please tell me.

Thanks!

### CODE REVIEW

**Comment by jainishshah17** [comment]
@mfuxi I think you will need to add network as well. Otherwise, all services will run only on one node of a swarm.

**Comment by eldada** [comment]
Thanks for this @mfuxi. Can you please join our contributors community by sining JFrog's CLA?
We need this to be able to merge any contribution. Thx!

**Comment by mfuxi** [comment]
@eldada I can't login, I don't have username and password.

**Comment by eldada** [comment]
You can create an account or go directly to the [CLA form](https://secure.echosign.com/public/hostedForm?formid=5IYKLZ2RXB543N)

**Comment by eldada** [comment]
@mfuxi - did you complete the CLA?

**Comment by mfuxi** [comment]
@eldada indeed, the CLA was signed.

**Pull request merged**
